config/routes.rb
Todolist::Application.routes.draw do

  root to: "lists#index"

  resources :lists, only: [:index, :new, :create] do
    resources :tasks, only: [:index, :new, :create, :update, :destroy]
  end

end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :name

  belongs_to :list
  accepts_nested_attributes_for :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def new
    @list = List.new
    redirect_to :root
  end

  def index
    @lists = List.all
    @list = List.new
    @task = Task.new
  end

  def create
    @list = List.create( params[:list] )
    flash[:notice] = "Your list has now been listed!"
    redirect_to :root
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def new
    @task = Task.new
    redirect_to :root
  end

  def index
    @tasks = Task.all
  end

  def destroy
    @task = Task.find params[:id]
    @task.destroy
    flash[:notice] = 'Your task has been destroyed!'
    redirect_to :root
  end

  def update
    @task = Task.find params[:id]
    @task.finished = params[:task][:finished]
    @task.save
    flash[:notice] = 'You updated a task!'
    redirect_to :root
  end

  def create
    @task = Task.create( params[:task] )
    @task.list_id = params[:list_id]
    @task.save
    flash[:notice] = 'Your task has now been listed!'
    redirect_to :root
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do | type, message | %>
  <%= message %>
<% end %>

<%= yield %>

</body>
</html>

app/views/lists/index.html.erb
<h1> List All the Lists!!</h1>
<ul>
  <% @lists.each do | list | %>
    <li><h3>List: <%= list.title %></h3></li>
    <ul>
      <% list_tasks = list.tasks.all %>
      <% list_tasks.each do | task | %>
        <li>
          <%= form_for [list, task], :html => {:class => 'checkbox_form'} do |f| %>
            <%= f.check_box :finished, onclick: '$(this).closest("form").submit()' %>
          <% end %>
          <p><%= task.name %></p>
          <%= form_for [list, task] do |f| %>
            <%= button_to 'Delete', list_tasks_path(list, task), method: :delete %>
          <% end %>
          <br>
        </li>
      <% end %>
    </ul>
    <br>
    <%= form_for list.tasks.new, url: list_tasks_path(list) do |f| %>
      <%= f.label :name, 'Name:', style: 'float: left' %>
      <%= f.text_field :name, style: 'float: left' %>
      <%= f.submit 'Add Task' %>
    <% end %>
    <br />
  <% end %>
</ul>
<br>
<%= form_for @list do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit 'Add List' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task List</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task.name %></li>
  <% end %>
</ul>